### ISSUE TITLE
not compatible with 2.2.1

### ISSUE THREAD

**Issue by HonkXL** [JustCarmen/webtrees-fancy-research-links#107]
It seems not to be compatible with webtrees 2.2.1 on PHP 8.3.
I got this message:

Fatal error in module: jc-fancy-research-links
Error: Call to undefined function JustCarmen\Webtrees\Module\FancyResearchLinks\app

**Comment by JustCarmen** [comment]
Fixed: https://github.com/JustCarmen/webtrees-fancy-research-links/commit/9e2e6d594e4ee4b6b39e92627b4abbb323f55d4f
