### ISSUE TITLE
Fancy Research Links seems not to work in webtrees 2.0.0

### ISSUE THREAD

**Issue by melizaa** [JustCarmen/webtrees-fancy-research-links#12]
In webtrees 2.0.0 Module administration when I try to configure Fancy Researche Links, I am transferred to the webtrees My page.

I do not see the Fancy Research Links in the indipage sidebar.

**Comment by hartenthaler** [comment]
It is great that you are on the way to make this module available again! Thanks a lot!

**Comment by JustCarmen** [comment]
This issue is solved with the release of version 2.0.0.

https://github.com/JustCarmen/webtrees-fancy-research-links/releases/tag/2.0.0
