### ISSUE TITLE
Sidebar content must be compatible - changes in Webtrees API

### ISSUE THREAD

**Issue by curtisdelicata** [JustCarmen/webtrees-fancy-research-links#13]
PHP Fatal error:  Declaration of JustCarmen\\WebtreesAddOns\\FancyResearchLinks\\FancyResearchLinksModule::getSidebarContent() must be compatible with Fisharebest\\Webtrees\\Module\\ModuleSidebarInterface::getSidebarContent(Fisharebest\\Webtrees\\Individual $individual) in /public_html/modules_v3/fancy_research_links/module.php on line 32

**Comment by curtisdelicata** [comment]
Adding Individual $individual fixes this error but still does not work due to the way it returns the variable?

**Comment by JustCarmen** [comment]
This issue is solved with the release of version 2.0.0.

https://github.com/JustCarmen/webtrees-fancy-research-links/releases/tag/2.0.0
