### ISSUE TITLE
Error after closing control panel menue

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-research-links#23]
I just updated your last modified files (knowing that there is no release for webtrees 2.0 up to now). Therefore feel free to close this issue without any comment. I can wait.
After closing the control panel menu, there is no way to avoid this error.
```
Undefined index: expanded-area …/modules_v4/jc-fancy-research-links/FancyResearchLinksModule.php:161
#0 …/modules_v4/jc-fancy-research-links/FancyResearchLinksModule.php(161): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/app/Http/RequestHandlers/ModuleAction.php(88): JustCarmen\Webtrees\Module\FancyResearchLinks\FancyResearchLinksModule->postAdminAction()
#2 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
#3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#4 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(226): Middleland\Dispatcher->handle()
```

**Comment by JustCarmen** [comment]
Hi, thanks for your feedback. I am working on the module right now to finally get it ready for webtrees 2. But I can't reproduce this error. Does this error occurs before you have set any options or after?

**Comment by hartenthaler** [comment]
After. I opened the control panel, made some changes, and the error occurred after pressing the save button. As far as I can see it is not depending on what was changed. It occurs always. 

I installed the module just by copy the files from your GitHub directory. 

Viele Grüße
Hermann 
---
Hermann Hartenthaler

**Comment by hartenthaler** [comment]
Thank you! Now everything is ok. I love your modules!
