### ISSUE TITLE
Plugins with POST and GET requests

### ISSUE THREAD

**Issue by z-yurets** [JustCarmen/webtrees-fancy-research-links#25]
Could you make plugins for these sites?
http://www.db.geroika.org.ua/ua/search.html
https://babynyar.org/ua/names
http://podvignaroda.ru/?#tab=navPeople_search
Here, search queries are transmitted as POST or GET requests. Unfortunately, my skills are not enough for this

**Comment by JustCarmen** [comment]
Yes I can make plugins for those sites but not the way you want. In the webtrees 1 version of the module I used a method to fill in forms on external websites with some javascript, but that method doesn't seem to work anymore. Those requests are blocked by external websites. So I had no other option than to turn those research links into 'link only' links. This means you can reach them from the individual page and keep them together with the other links, but they can't take any variable data and just provide a simple link to the external page.

**Comment by JustCarmen** [comment]
On second thought I think you beter make those (link only) plugins yourself and send me a pull request. I cannot write a plugin label in Russian or Ukranian.

**Comment by z-yurets** [comment]
Wrote to support these sites with a request to suggest a possible solution. I did not receive an answer, so I will do as you advised. Unfortunately
