### ISSUE TITLE
New: Research link for Chronicling America

### ISSUE THREAD

**Issue by Manja-S** [JustCarmen/webtrees-fancy-research-links#27]
About the website [Chronicling America](https://chroniclingamerica.loc.gov/):
Search America's historic newspaper pages from 1777-1963 or use the U.S. Newspaper Directory to find information about American newspapers published between 1690-present.

Demo: https://www.schledorn.nl/webtrees/tree/Schledorn/individual/I31/Marie-van-der-Heiden

I had to save as .txt instead of .php to be able to share here, so the file extension needs to be renamed.
[ChroniclingAmericaPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/6880472/ChroniclingAmericaPlugin.txt)

Edit: I modified the plugin to add the birth year as 'from' date for searches and added 'sort by date'.

**Comment by JustCarmen** [comment]
Thank you!
