### ISSUE TITLE
 list of variables available to use in own new plugins

### ISSUE THREAD

**Issue by ghezibde** [JustCarmen/webtrees-fancy-research-links#32]
Hello JustCarmen,

First of all, i want to thank you so much for this great module.
I've using it in its previous version (Webtrees 1.7....) and i'm going to write the plugins i need for my ghezibde website.
Would it please be possible to have a list of variables available to use in the own plugins i wand to build as described in 1.7 version page https://justcarmen.nl/modules-webtrees-1/fancy-research-links/ ?
Thanks and regards,
Andre
(for example, i look in every already available plugin to find example about places (birth, christening, death or burial but could find)

**Comment by ghezibde** [comment]
I just put plugins online on our webtrees website.
Great, wonderful, will help us a lot on everyday researches.
The only limit i met is i was unable to use places as parameters : $death['place'] or $birth['place'] make a type mismatch error when used.
I would like to use those as parameters to refine results of searches, would it be possible.
Thanks for your work and thanks to share it !
Regards

**Comment by JustCarmen** [comment]
Hi, thanks for your feedback.

I've extended the description with a list of variables: https://justcarmen.nl/modules-webtrees-2/fancy-research-links/

The list is also available [at this place](https://github.com/JustCarmen/webtrees-fancy-research-links)

Your problem with $death['place'] and $birth['place'] was a bug which is already [fixed](https://github.com/JustCarmen/webtrees-fancy-research-links/commit/6215930222f6d66bf4bdf93dffd54d3c73e75e33). It will added to the next release which I will bring out soon.
