### ISSUE TITLE
3 New Plugins

### ISSUE THREAD

**Issue by Manja-S** [JustCarmen/webtrees-fancy-research-links#34]
I made 3 new plugins and i'd like to share them here. They'd have to be renamed to .php to make them work.

* Rijckheyt centrum voor regionale geschiedenis Brunssum, Gulpen-Wittem, Heerlen, Nuth, Simpelveld en Voerendaal
* AEZEL (Erfgoed Limburg)
* Erfgoed Enschede

[RijckheytPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/7121226/RijckheytPlugin.txt)
[AezelPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/7121227/AezelPlugin.txt)
[ErfgoedEnschedePlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/7121228/ErfgoedEnschedePlugin.txt)

**Comment by JustCarmen** [comment]
Thanks! I've added these plugins. They will be available in the next release.

Dank je wel :)
