### ISSUE TITLE
empty places with 'unknown' value

### ISSUE THREAD

**Issue by ghezibde** [JustCarmen/webtrees-fancy-research-links#35]
When using an empty or undefined place, $birth['place'] or $death['place'] does does return an empty string but a string with 'unknown' value.
Is that on purpose ?
the linked websites would rather accept an empty string.
The following lines in "public static function" of the plugin solve the problem.
        $birthplace = $birth['place'];
        if ($birth['place'] == I18N::translate('unknown')) {
                $birthplace = '';
        }
        //
        $deathplace = $death['place'];
        if ($death['place'] == I18N::translate('unknown')) {
                $deathplace = '';
        }
then use $birthplace and $deathplace instaed of $birth['place']  and $death['place'] in the return url string.

**Comment by JustCarmen** [comment]
Which version do you use? This is solved in the 2.0.1 release.

https://github.com/JustCarmen/webtrees-fancy-research-links/commit/d568c4b7981d4f2c068e648c495bb62e32fcceee

**Comment by ghezibde** [comment]
Right, 2.0.1 was not totally installed.
Now done. 
Warning about same case for name : empty name return @N.N. value (2.0.1)
