### ISSUE TITLE
second, third or fourth members of global place names

### ISSUE THREAD

**Issue by ghezibde** [JustCarmen/webtrees-fancy-research-links#36]
Hello,
If we accept places names in gedcom are labelled as town, county, state, Country, would it be possible to get use of county, state, country values of place names ?
(more generally, use second, third or fourth values of global place names)

**Comment by JustCarmen** [comment]
Good suggestion, but at the moment this is not possible. I need to extend the module in order to use other parts of the place names in a (custom) plugin.

**Comment by JustCarmen** [comment]
I looked into this and on reflection decided not to implement it. It is very difficult, if not impossible, to get the same parts of the place name all the time.

Let me give you an example.
In the Netherlands a place often consists of 3 parts (city, county, country) while in the United States a place often consists of 4 parts (city, county, state, country). In either situation, there could be more parts, but this is the simplified version to make it clear.

The third part in the place name in the Netherlands gives the country as the result, while the third part in the place name in the US gives the state as the result.

And this is just a simplified example. As you can imagine, there are place names that have 5 or more parts. I cannot determine which part is the country and which part is the city or town.

The first part of the place name is often the place where the event took place and is therefore the most useful part of the place to use in the research links. Of course you can edit the generated place name afterwards on the research website itself.
