### ISSUE TITLE
Use of married name for plugins

### ISSUE THREAD

**Issue by Manja-S** [JustCarmen/webtrees-fancy-research-links#45]
I'm experiment with a plugin for [SSDI (Social Security Death Index)](https://en.wikipedia.org/wiki/Social_Security_Death_Index), a database from USA (I chose to search the records through FamilySearch). A problem I'm encountering is that in the USA [married women](https://www.schledorn.nl/webtrees/tree/Schledorn/individual/I162/Cecile-Alma-Cecile-Huffman) usually aren't registered under their [birth name](https://www.familysearch.org/search/record/results?count=20&q.birthLikeDate.from=1903&q.birthLikeDate.to=1903&q.givenName=Cecile&q.surname=Huffman&f.collectionId=1202535), but under their [married surname](https://www.familysearch.org/search/record/results?count=20&q.birthLikeDate.from=1903&q.birthLikeDate.to=1903&q.givenName=Cecile&q.surname=Schledorn&f.collectionId=1202535). Is there a way to implement this in the plugin?

**Comment by JustCarmen** [comment]
I linked to the wrong issue by accident. Don't know how to remove it. But you can ignore it.

**Comment by JustCarmen** [comment]
I've added support for the marriage name. You can add it to your link by using $name['msurname']

**Comment by Manja-S** [comment]
You might want to add this variable to pt. 4 in the [Introduction](https://github.com/JustCarmen/webtrees-fancy-research-links).

**Comment by JustCarmen** [comment]
Thanks. You are right. But I see the text is outdated anyway, so I've made a new issue for this.

**Comment by Manja-S** [comment]
Thank you for all your work!
