### ISSUE TITLE
Updated: Rootsweb plugin

### ISSUE THREAD

**Issue by Manja-S** [JustCarmen/webtrees-fancy-research-links#51]
Replaced line 14: _return 'Rootsweb (link only)';_ with _return 'Rootsweb (' . I18N::translate('link only') . ')';_ to enable translation.

[RootsWebPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8125651/RootsWebPlugin.txt)
I had to save as .txt instead of .php to be able to share here, so the file extension needs to be renamed.

**Comment by JustCarmen** [comment]
Thanks!
