### ISSUE TITLE
New plugins

### ISSUE THREAD

**Issue by Manja-S** [JustCarmen/webtrees-fancy-research-links#52]
I made some new plugins (and then had to rework them for 2.1.0 :-) ), perhaps they can be added to the project:
- [AchelseKluisBidprentjesPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8125986/AchelseKluisBidprentjesPlugin.txt): To search the prayer card collection from the Achelse Kluis Abbey. I added a tooltip to the label, this might need a review as I'm not sure I did it the right way.
- [CBGverzamelingenPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8125852/CBGverzamelingenPlugin.txt): Digitally accessible sources at the Dutch Centraal Bureau voor Genealogie (CBG)
- [FacebookPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8125875/FacebookPlugin.txt): To check if a person has a Facebook profile and perhaps connect with removed cousins.
- [GenealIXPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8125912/GenealIXPlugin.txt): Links to Dutch vital records per place name.
- [NederlandsBidprentjesArchiefPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8125995/NederlandsBidprentjesArchiefPlugin.txt): Another collection of prayer cards.
- [NewspapersComPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8126041/NewspapersComPlugin.txt): The largest online newspaper archive from around the United States and beyond.
- [OorlogsbronnenPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8126101/OorlogsbronnenPlugin.txt): A central online access to original sources, information and knowledge about the Second World War in the Netherlands
- [OpenArchievenZoekBidprentjesPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8126119/OpenArchievenZoekBidprentjesPlugin.txt): Search for prayer cards at the Dutch Open Archives website.
- [SSDIPlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8126157/SSDIPlugin.txt): A database of death records created from the United States Social Security Administration 's Death Master File Extract. This one has a tooltip as well, so maybe it needs a review too.
- [WikiTreePlugin.txt](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8126254/WikiTreePlugin.txt): A collaborative family tree.

I had to save as .txt instead of .php to be able to share here, so the file extensions need to be renamed.

Some of the remarks I added to the labels will have to be translated, but I believe that this can't be done until they are part of the project.

**Comment by JustCarmen** [comment]
Thank you very much Manja!

I've added the new plugins to the module with only one small adjustment.
