### ISSUE TITLE
Suggestion—Find a Grave

### ISSUE THREAD

**Issue by WGroleau** [JustCarmen/webtrees-fancy-research-links#58]
[FindAGravePlugin.php.zip](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8704557/FindAGravePlugin.php.zip)

Looks lie Find a Grave has changed their search syntax.  I edited my copy of the plugin to the attached and find it working well.

**Comment by JustCarmen** [comment]
Thanks!
