### ISSUE TITLE
Suggestion—FamilySearch

### ISSUE THREAD

**Issue by WGroleau** [JustCarmen/webtrees-fancy-research-links#59]
Using only names in FamilySearch usually gets too many hits to be useful.  I've attached a version I created that I find more useful
[FamilySearchPlugin.php.zip](https://github.com/JustCarmen/webtrees-fancy-research-links/files/8704895/FamilySearchPlugin.php.zip)
.

**Comment by JustCarmen** [comment]
Thanks!
