### ISSUE TITLE
MensenlinqPlugin doesn't work anymore

### ISSUE THREAD

**Issue by TheDutchJewel** [JustCarmen/webtrees-fancy-research-links#65]
Yesterday the website of mensenlinq.nl is renewed, and now the MensenlinqPlugin doesn't work anymore.

Even after modifying the return string it does not work:
```
return 'https://mensenlinq.nl/?passed_date_from=1970-01-01&passed_date_to=' .
date('Y-m-d') .
'&page=1&per_page=24&published_date_from=' .
'&first_name=' . $name['first'] . '&last_name=' . $name['surname'];
```

**Comment by TheDutchJewel** [comment]
Mensenlinq.nl is working again with above code.

But I've adapted the return string to the new website URL syntax:
```
return 'https://mensenlinq.nl/overlijdensberichten/?' .
'first_name=' . $name['first'] . '&last_name=' . $name['surname'] .
'&passed_date_from=1970-01-01&passed_date_to=' . date('Y-m-d');
```
See also [pull request #3](https://github.com/JustCarmen/webtrees-fancy-research-links/pull/66)

**Comment by TheDutchJewel** [comment]
Same problem again.

A temporary solution is to change `https://mensenlinq.nl/overlijdensberichten/?` into `https://account.mensenlinq.nl/api/person?`, which gives the contents of a .json file.

**Comment by JustCarmen** [comment]
I'm afraid this is not a solution. It is no longer possible to autocomplete the search form. So I will change the link to a 'link only' link.  Clicking on the link will take you to the search form where you can manually fill in the search details.

**Comment by JustCarmen** [comment]
It seems the code from @TheDutchJewel in https://github.com/JustCarmen/webtrees-fancy-research-links/issues/65#issuecomment-1227259567 is still working. So I don't think it is necessary to change the link into a readonly link at the moment.

**Comment by TheDutchJewel** [comment]
I know. It has been working again since this weekend. I wanted to wait a little longer (till next week) to respond to see how stable the situation remains.

**Comment by JustCarmen** [comment]
By now we are a couple of weeks on but the link is still working, so I assume it will stay that way.
