### ISSUE TITLE
Error in log, recent version

### ISSUE THREAD

**Issue by heiler** [JustCarmen/webtrees-fancy-research-links#67]
`<b>foreach() argument must be of type array|object, null given …/modules_v4/jc-fancy-research-links/resources/views/sidebar.phtml:23</b> <b>#0 …/modules_v4/jc-fancy-research-links/resources/views/sidebar.phtml(23): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()</b> #1 …/app/View.php(183): include(&#039;...&#039;) #2 …/app/View.php(278): Fisharebest\Webtrees\View-&gt;render() #3 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make() <b>#4 …/modules_v4/jc-fancy-research-links/FancyResearchLinksModule.php(249): view()</b> #5 …/resources/views/individual-page-sidebars.phtml(25): JustCarmen\Webtrees\Module\FancyResearchLinks\FancyResearchLinksModule-&gt;getSidebarContent() #6 …/app/View.php(183): include(&#039;...&#039;) #7 …/app/View.php(278): Fisharebest\Webtrees\View-&gt;render() #8 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make() #9 …/resources/views/individual-page.phtml(60): view() #10 …/app/View.php(183): include(&#039;...&#039;) #11 …/app/View.php(278): Fisharebest\Webtrees\View-&gt;render() #12 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make() #13 …/app/Http/ViewResponseTrait.php(50): view() #14 …/app/Http/RequestHandlers/IndividualPage.php(140): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage-&gt;viewResponse() #15 …/app/Http/Middleware/RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage-&gt;handle() #16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process() #17 …/app/Module/CheckForNewVersion.php(115): Middleland\Dispatcher-&gt;handle() #18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion-&gt;process() #19 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher-&gt;handle() #20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process() #21 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #22 …/app/Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch() #23 …/app/Http/Middleware/Router.php(153): Fisharebest\Webtrees\Webtrees::dispatch() #24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process() #25 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher-&gt;handle() #26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process() #27 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher-&gt;handle() #28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags-&gt;process() #29 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher-&gt;handle() #30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process() #31 …/app/Http/Middleware/CheckForNewVersion.php(65): Middleland\Dispatcher-&gt;handle() #32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion-&gt;process() #33 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle() #34 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #35 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection-&gt;transaction() #36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process() #37 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher-&gt;handle() #38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process() #39 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher-&gt;handle() #40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process() #41 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle() #42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process() #43 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher-&gt;handle() #44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process() #45 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher-&gt;handle() #46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process() #47 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle() #48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process() #49 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher-&gt;handle() #50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process() #51 …/app/Http/Middleware/BadBotBlocker.php(233): Middleland\Dispatcher-&gt;handle() #52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process() #53 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher-&gt;handle() #54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process() #55 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher-&gt;handle() #56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process() #57 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher-&gt;handle() #58 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process() #59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process() #60 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher-&gt;handle() #61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process() #62 …/app/Http/Middleware/BaseUrl.php(79): Middleland\Dispatcher-&gt;handle() #63 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process() #64 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle() #65 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process() #66 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle() #67 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process() #68 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle() #69 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process() #70 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #71 …/app/Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch() #72 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() #73 …/index.php(51): Fisharebest\Webtrees\Webtrees-&gt;httpRequest() #74 {main}`

**Comment by JustCarmen** [comment]
Thanks for reporting this issue. I am working on it. See: #68 for further information.
