### ISSUE TITLE
Too few arguments: OpenArchievenPlugin.php:27

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-research-links#77]
> Too few arguments to function JustCarmen\Webtrees\Module\FancyResearchLinks\Plugin\OpenArchievenPlugin::researchLink(), 1 passed in …/modules_v4/jc-fancy-research-links/resources/views/sidebar.phtml on line 42 and exactly 3 expected …/modules_v4/jc-fancy-research-links/plugins/OpenArchievenPlugin.php:27
> #0 …/modules_v4/jc-fancy-research-links/resources/views/sidebar.phtml(42): JustCarmen\Webtrees\Module\FancyResearchLinks\Plugin\OpenArchievenPlugin::researchLink()

**Comment by Manja-S** [comment]
Please see is this solves your problem: https://github.com/JustCarmen/webtrees-fancy-research-links/issues/50#issuecomment-1049038385

**Comment by JustCarmen** [comment]
Manja is right. This is an old plugin that has been removed from the module about a year ago and has been replaced with three new plugins:
- OpenArchievenStandaardPlugin;
- OpenArchievenTranscriptiesPlugin
- OpenArchievenZoekBidprentjesPlugin

Changes have recently been made to all plugins, but obviously they have not been made to the discontinued OpenArchivesPlugin. That is why it is only now dropping out with an error message.

**Comment by hartenthaler** [comment]
ok. The old file was deleted. Thank you!
