### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by remkot** [JustCarmen/webtrees-fancy-research-links#94]
When i will install the research-links on version 2.1.20 i get this:

Fatal error: Declaration of JustCarmen\Webtrees\Module\FancyResearchLinks\FancyResearchLinksModule::sidebarTitle(): string must be compatible with Fisharebest\Webtrees\Module\ModuleSidebarInterface::sidebarTitle(Fisharebest\Webtrees\Individual $individual): string in /volume1/web/remkot.nl/stamboomwt/modules_v4/jc-fancy-research-links/FancyResearchLinksModule.php on line 215 Fatal error: Uncaught Error: Typed static property Fisharebest\Webtrees\I18N::$locale must not be accessed before initialization in /volume1/web/remkot.nl/stamboomwt/app/I18N.php:365 Stack trace: #0 /volume1/web/remkot.nl/stamboomwt/app/Factories/TimestampFactory.php(50): Fisharebest\Webtrees\I18N::locale() https://github.com/JustCarmen/webtrees-theme-justlight/issues/1 /volume1/web/remkot.nl/stamboomwt/app/Factories/TimestampFactory.php(81): Fisharebest\Webtrees\Factories\TimestampFactory->make(1713207823, Object(Fisharebest\Webtrees\User)) https://github.com/JustCarmen/webtrees-theme-justlight/issues/2 /volume1/web/remkot.nl/stamboomwt/app/SessionDatabaseHandler.php(89): Fisharebest\Webtrees\Factories\TimestampFactory->now() https://github.com/JustCarmen/webtrees-theme-justlight/issues/3 [internal function]: Fisharebest\Webtrees\SessionDatabaseHandler->write('8e657667648c072...', 'initiated|b:1;_...') https://github.com/JustCarmen/webtrees-theme-justlight/issues/4 [internal function]: session_write_close() https://github.com/JustCarmen/webtrees-theme-justlight/issues/5 {main} thrown in /volume1/web/remkot.nl/stamboomwt/app/I18N.php on line 365

can you help me with this? Thanks!

**Comment by JustCarmen** [comment]
What version of this module are you using? It looks like you are using a really old version of this module.

Install the latest version to see if the problem disappears:

https://github.com/JustCarmen/webtrees-fancy-research-links/releases/latest

**Comment by remkot** [comment]
Hello,
I thought I downloaded the latest version from the link in your website. It works with this one. 
Thank you very much!
